= docker-fakesmtp
:author: Guillaume Husta
:icons: font
:sectnums:
:toc: auto

Another docker image for FakeSMTP (https://github.com/Nilhcem/FakeSMTP)

== Overview

https://github.com/Nilhcem/FakeSMTP[FakeSMTP] is a Free Fake SMTP Server with GUI for testing emails in applications easily. It is written in Java.

== Docker

=== Dockerfile

See original https://github.com/Nilhcem/FakeSMTP/blob/master/Dockerfile[there].

=== Usage

This allows you to run a SMTP server for testing applications which send mail. Each mail is written to a file in `/var/mail`

Starting a container :

----
docker run -d -p 2525:25 -v /tmp/fakemail:/var/mail ghusta/fakesmtp:2.0
----

See also docker usage on the https://github.com/Nilhcem/FakeSMTP#usage-on-docker[original project].

== Refactoring

I use *openjdk* as base image, as *java* image is now _deprecated_ (see https://hub.docker.com/_/java/).
Furthermore, I use the JRE version, as JDK is not necessary (image _openjdk:8-jre_ for example).

=== Available OpenJDK Docker images

Not all versions or alternatives (jdk, jre, slim, etc.) are available.

See which ones there : https://github.com/docker-library/openjdk/issues/272[Update to version X on base os Y].

At the moment, OpenJDK 8 and 11 Docker images are based on the versions published here : https://adoptopenjdk.net/upstream.html .